---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: c:/opscode/chefdk

platforms:
  - name: windows-2016
    driver_config:
      box: tas50/windows_2016
      box_url: https://app.vagrantup.com/tas50/boxes/windows_2016

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[win_proxy]
      - recipe[chefdk_bootstrap]
      - recipe[chefdk_bootstrap::fix_profile]
    attributes:
      chefdk_bootstrap:
        package:
          gitconfig: true
