#!/usr/bin/env bash

# Copyright 2015 Nordstrom, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -o nounset -o pipefail

CHEFDK_TARGET_VERSION=0.14.25

function prompt_continue () {
  echo ""
  echo "chefdk_bootstrap encountered an error in the previous step."
  read -p "Ignore the error and contine with installation? [yN] " </dev/tty
  case "$REPLY" in
    [yY]*) return
      ;;
    *) echo "Not cleaning up $tempInstallDir; exiting."
      exit 2
      ;;
  esac
}

# If the user has not passed in a cookbook name use 'chefdk_bootstrap' for the cookbook
bootstrapCookbook=${1:-chefdk_bootstrap}

# If the user has passed in a private supermarket url then add it to the Berksfile
private_source=${2:+source \'$2\'}

clear

# introduction
cat <<EOF;
This script will:

1. Install the latest ChefDK package
2. Download the 'chefdk_bootstrap' cookbook via Berkshelf
3. Run 'chef-client' to install the rest of the tools you will need
EOF

tempInstallDir=`mktemp -d -t chefdk_bootstrap`

# create Berksfile so that we can install the correct cookbook dependencies
cat > "${tempInstallDir}/Berksfile" <<EOF;
source 'https://supermarket.chef.io'
$private_source

cookbook '$bootstrapCookbook'
EOF

# create client.rb file so that Chef client can find its dependant cookbooks
cat > "${tempInstallDir}/client.rb" <<EOF;
cookbook_path File.join(Dir.pwd, 'berks-cookbooks')
EOF

cat <<EOF;

** Installing ChefDK

EOF

chefdk_installed_version=$(chef --version 2>/dev/null |awk '/Chef Development Kit Version:/ {print $NF}')
case "$chefdk_installed_version" in
  "$CHEFDK_TARGET_VERSION")
    echo "ChefDK ${CHEFDK_TARGET_VERSION} is already installed, skipping"
    INSTALL_CHEFDK=0;;
  "")
    # ChefDK is not installed
    INSTALL_CHEFDK=1;;
  *)
    echo "Replacing ChefDK ${chefdk_installed_version} with ${CHEFDK_TARGET_VERSION}"
    echo "Uninstalling ChefDK ${chefdk_installed_version}..."
    sudo rm -rf /opt/chefdk
    sudo find /usr/bin /usr/local/bin -lname '/opt/chefdk/*' -delete
    rm -rf ~/.chefdk
    INSTALL_CHEFDK=1;;
esac
if [[ "$INSTALL_CHEFDK" -eq 1 ]]
then
  echo "Installing ChefDK ${CHEFDK_TARGET_VERSION}"
  curl --silent --show-error https://omnitruck.chef.io/install.sh | \
    sudo -E bash -s -- -c stable -P chefdk -v ${CHEFDK_TARGET_VERSION} || prompt_continue
fi

echo "Downloading cookbook dependencies with Berkshelf"
cd "$tempInstallDir" || prompt_continue
chef exec berks vendor || prompt_continue

# Pass optional attributes to chef-client
# This is a temporary interface and will change in 2.0 when we support named parameters (Issue #74)
if [ -n "${CHEFDK_BOOTSTRAP_JSON_ATTRIBUTES:-}" ]
then
  attributeParameter=" --json-attributes $CHEFDK_BOOTSTRAP_JSON_ATTRIBUTES"
fi

echo "Running chef-client (installed by ChefDK) to bootstrap this machine"
sudo -E chef-client -z -l error -c "${tempInstallDir}/client.rb" -o "$bootstrapCookbook" ${attributeParameter:-} || prompt_continue

# cleanup
cd - || prompt_continue
sudo rm -rf "$tempInstallDir"

# End message to direct Mac users to last step in set up
cat <<EOF;
You're almost done!!! You just need to edit your shell startup script to set up
chefdk environment variables for each login. See this page:
https://github.com/chef/chef-dk#using-chefdk-as-your-primary-development-environment
EOF
